// scripts/seed-bienes.ts
// Inserta 30 bienes de uso de ejemplo sin tocar el resto de la BD
import { PrismaLibSql } from '@prisma/adapter-libsql'
import { PrismaClient } from '@prisma/client'
import * as dotenv from 'dotenv'
dotenv.config()

async function main() {
  const adapter = new PrismaLibSql({
    url: process.env.TURSO_DATABASE_URL!,
    authToken: process.env.TURSO_AUTH_TOKEN!,
  })
  const prisma = new PrismaClient({ adapter } as any)

  const biz = await prisma.business.findFirst()
  if (!biz) throw new Error('No hay negocio en la BD')
  const bid = biz.id
  console.log(`📌 Negocio: ${biz.name}`)

  // Borrar bienes existentes para no duplicar
  const deleted = await prisma.bienDeUso.deleteMany({ where: { businessId: bid } })
  console.log(`🗑️  Bienes anteriores eliminados: ${deleted.count}`)

  function fecha(year: number, month: number, day: number) {
    return new Date(year, month - 1, day)
  }

  const bienes = [
    // ── Equipos informáticos ─────────────────────────────────────
    {
      nombre: 'MacBook Pro 16"',
      categoria: 'Equipos informáticos',
      marca: 'Apple',
      valorAdquisicion: 1_800_000,
      valorResidual: 360_000,
      depreciacionAcumulada: 450_000,
      fechaAdquisicion: fecha(2023, 3, 15),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'MacBook Air M2',
      categoria: 'Equipos informáticos',
      marca: 'Apple',
      valorAdquisicion: 1_200_000,
      valorResidual: 240_000,
      depreciacionAcumulada: 200_000,
      fechaAdquisicion: fecha(2023, 8, 20),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'MacBook Air M2',
      categoria: 'Equipos informáticos',
      marca: 'Apple',
      valorAdquisicion: 1_200_000,
      valorResidual: 240_000,
      depreciacionAcumulada: 200_000,
      fechaAdquisicion: fecha(2023, 8, 20),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Monitor LG 27" 4K',
      categoria: 'Equipos informáticos',
      marca: 'LG',
      valorAdquisicion: 480_000,
      valorResidual: 48_000,
      depreciacionAcumulada: 96_000,
      fechaAdquisicion: fecha(2023, 5, 10),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Monitor LG 27" 4K',
      categoria: 'Equipos informáticos',
      marca: 'LG',
      valorAdquisicion: 480_000,
      valorResidual: 48_000,
      depreciacionAcumulada: 96_000,
      fechaAdquisicion: fecha(2023, 5, 10),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Servidor NAS',
      categoria: 'Equipos informáticos',
      marca: 'Synology',
      valorAdquisicion: 650_000,
      valorResidual: 65_000,
      depreciacionAcumulada: 130_000,
      fechaAdquisicion: fecha(2023, 2, 1),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Impresora Multifunción',
      categoria: 'Equipos informáticos',
      marca: 'HP',
      valorAdquisicion: 180_000,
      valorResidual: 18_000,
      depreciacionAcumulada: 54_000,
      fechaAdquisicion: fecha(2022, 11, 8),
      vidaUtilMeses: 48,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Router Cisco Meraki',
      categoria: 'Equipos informáticos',
      marca: 'Cisco',
      valorAdquisicion: 320_000,
      valorResidual: 32_000,
      depreciacionAcumulada: 64_000,
      fechaAdquisicion: fecha(2023, 1, 18),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },

    // ── Mobiliario ───────────────────────────────────────────────
    {
      nombre: 'Escritorio Ejecutivo',
      categoria: 'Mobiliario',
      marca: null,
      valorAdquisicion: 85_000,
      valorResidual: 8_500,
      depreciacionAcumulada: 17_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Escritorio Ejecutivo',
      categoria: 'Mobiliario',
      marca: null,
      valorAdquisicion: 85_000,
      valorResidual: 8_500,
      depreciacionAcumulada: 17_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Escritorio Ejecutivo',
      categoria: 'Mobiliario',
      marca: null,
      valorAdquisicion: 85_000,
      valorResidual: 8_500,
      depreciacionAcumulada: 17_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Silla Ergonómica',
      categoria: 'Mobiliario',
      marca: 'Herman Miller',
      valorAdquisicion: 95_000,
      valorResidual: 9_500,
      depreciacionAcumulada: 19_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Silla Ergonómica',
      categoria: 'Mobiliario',
      marca: 'Herman Miller',
      valorAdquisicion: 95_000,
      valorResidual: 9_500,
      depreciacionAcumulada: 19_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Silla Ergonómica',
      categoria: 'Mobiliario',
      marca: 'Herman Miller',
      valorAdquisicion: 95_000,
      valorResidual: 9_500,
      depreciacionAcumulada: 19_000,
      fechaAdquisicion: fecha(2023, 4, 5),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Mesa de Reuniones',
      categoria: 'Mobiliario',
      marca: null,
      valorAdquisicion: 220_000,
      valorResidual: 22_000,
      depreciacionAcumulada: 44_000,
      fechaAdquisicion: fecha(2023, 6, 12),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Estantería Metálica',
      categoria: 'Mobiliario',
      marca: null,
      valorAdquisicion: 45_000,
      valorResidual: 4_500,
      depreciacionAcumulada: 9_000,
      fechaAdquisicion: fecha(2022, 9, 3),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },

    // ── Vehículos ────────────────────────────────────────────────
    {
      nombre: 'Volkswagen Amarok',
      categoria: 'Vehículos',
      marca: 'Volkswagen',
      valorAdquisicion: 6_800_000,
      valorResidual: 1_360_000,
      depreciacionAcumulada: 1_360_000,
      fechaAdquisicion: fecha(2022, 6, 20),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Renault Kangoo',
      categoria: 'Vehículos',
      marca: 'Renault',
      valorAdquisicion: 3_200_000,
      valorResidual: 640_000,
      depreciacionAcumulada: 800_000,
      fechaAdquisicion: fecha(2021, 11, 15),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },

    // ── Maquinaria ───────────────────────────────────────────────
    {
      nombre: 'Aire Acondicionado Split 6000',
      categoria: 'Maquinaria',
      marca: 'Inverter',
      valorAdquisicion: 380_000,
      valorResidual: 38_000,
      depreciacionAcumulada: 76_000,
      fechaAdquisicion: fecha(2023, 1, 10),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Aire Acondicionado Split 6000',
      categoria: 'Maquinaria',
      marca: 'Inverter',
      valorAdquisicion: 380_000,
      valorResidual: 38_000,
      depreciacionAcumulada: 76_000,
      fechaAdquisicion: fecha(2023, 1, 10),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Proyector 4K',
      categoria: 'Maquinaria',
      marca: 'Epson',
      valorAdquisicion: 420_000,
      valorResidual: 42_000,
      depreciacionAcumulada: 84_000,
      fechaAdquisicion: fecha(2023, 3, 22),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Fotocopiadora',
      categoria: 'Maquinaria',
      marca: 'Ricoh',
      valorAdquisicion: 890_000,
      valorResidual: 89_000,
      depreciacionAcumulada: 178_000,
      fechaAdquisicion: fecha(2022, 8, 5),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'UPS 3000VA',
      categoria: 'Maquinaria',
      marca: 'APC',
      valorAdquisicion: 250_000,
      valorResidual: 25_000,
      depreciacionAcumulada: 50_000,
      fechaAdquisicion: fecha(2023, 2, 14),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },

    // ── Instalaciones ────────────────────────────────────────────
    {
      nombre: 'Cableado Estructurado Cat6',
      categoria: 'Instalaciones',
      marca: null,
      valorAdquisicion: 140_000,
      valorResidual: 14_000,
      depreciacionAcumulada: 28_000,
      fechaAdquisicion: fecha(2022, 12, 1),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Sistema CCTV',
      categoria: 'Instalaciones',
      marca: null,
      valorAdquisicion: 580_000,
      valorResidual: 58_000,
      depreciacionAcumulada: 116_000,
      fechaAdquisicion: fecha(2023, 1, 28),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Instalación Eléctrica Industrial',
      categoria: 'Instalaciones',
      marca: null,
      valorAdquisicion: 320_000,
      valorResidual: 32_000,
      depreciacionAcumulada: 64_000,
      fechaAdquisicion: fecha(2022, 7, 15),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Rack de Servidores 42U',
      categoria: 'Instalaciones',
      marca: null,
      valorAdquisicion: 480_000,
      valorResidual: 48_000,
      depreciacionAcumulada: 96_000,
      fechaAdquisicion: fecha(2022, 12, 10),
      vidaUtilMeses: 120,
      activo: true,
      businessId: bid,
    },

    // ── Herramientas ─────────────────────────────────────────────
    {
      nombre: 'Kit Herramientas Electrónicas',
      categoria: 'Herramientas',
      marca: null,
      valorAdquisicion: 45_000,
      valorResidual: 4_500,
      depreciacionAcumulada: 9_000,
      fechaAdquisicion: fecha(2023, 5, 3),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Kit Herramientas Electrónicas',
      categoria: 'Herramientas',
      marca: null,
      valorAdquisicion: 45_000,
      valorResidual: 4_500,
      depreciacionAcumulada: 9_000,
      fechaAdquisicion: fecha(2023, 5, 3),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Multímetro Digital',
      categoria: 'Herramientas',
      marca: 'Fluke',
      valorAdquisicion: 85_000,
      valorResidual: 8_500,
      depreciacionAcumulada: 17_000,
      fechaAdquisicion: fecha(2023, 4, 18),
      vidaUtilMeses: 60,
      activo: true,
      businessId: bid,
    },
    {
      nombre: 'Soldadora TIG',
      categoria: 'Herramientas',
      marca: 'Lincoln Electric',
      valorAdquisicion: 420_000,
      valorResidual: 42_000,
      depreciacionAcumulada: 84_000,
      fechaAdquisicion: fecha(2022, 10, 7),
      vidaUtilMeses: 84,
      activo: true,
      businessId: bid,
    },
  ]

  const { count } = await prisma.bienDeUso.createMany({ data: bienes })
  console.log(`✅ Bienes de uso creados: ${count}`)

  const total = bienes.reduce((s, b) => s + b.valorAdquisicion, 0)
  console.log(`💰 Valor de adquisición total: $${total.toLocaleString('es-AR')}`)

  await prisma.$disconnect()
}

main().catch(e => { console.error(e); process.exit(1) })
